

efl_statistics_td_column_index = {
    'nationality': 0,
    'position': 1,
    'age': 2,
    'games': 3,
    'games_starts': 4,
    'minutes': 5,
    'minutes_90s': 6,
    'goals': 7,
    'assists': 8,
    'goals_pens': 9,
    'pens_made': 10,
    'pens_att': 11,
    'cards_yellow': 12,
    'cards_red': 13,
    'goals_per90': 14,
    'assists_per90': 15,
    'goals_assists_per90': 16,
    'goals_pens_per90': 17,
    'goals_assists_pens_per90': 18
}


fa_statistics_td_column_index = {
    'nationality': 0,
    'position': 1,
    'age': 2,
    'games': 3,
    'games_starts': 4,
    'minutes': 5,
    'minutes_90s': 6,
    'goals': 7,
    'assists': 8,
    'goals_pens': 9,
    'pens_made': 10,
    'pens_att': 11,
    'cards_yellow': 12,
    'cards_red': 13,
    'goals_per90': 14,
    'assists_per90': 15,
    'goals_assists_per90': 16,
    'goals_pens_per90': 17,
    'goals_assists_pens_per90': 18
}

epl_statistics_td_column_index = {
    'nationality': 0,
    'position': 1,
    'age': 2,
    'games': 3,
    'games_starts': 4,
    'minutes': 5,
    'minutes_90s': 6,
    'goals': 7,
    'assists': 8,
    'goals_pens': 9,
    'pens_made': 10,
    'pens_att': 11,
    'cards_yellow': 12,
    'cards_red': 13,
    'goals_per90': 14,
    'assists_per90': 15,
    'goals_assists_per90': 16,
    'goals_pens_per90': 17,
    'goals_assists_pens_per90': 18,
    'xg': 19,
    'npxg': 20,
    'xa': 21,
    'xa_per90': 22,
    'xg_per90': 23,
    'xg_xa_per90': 24,
    'npxg_per90': 25,
    'npxg_xa_per90': 26
}


ucl_statistics_td_column_index = {
    'nationality': 0,
    'position': 1,
    'age': 2,
    'games': 3,
    'games_starts': 4,
    'minutes': 5,
    'minutes_90s': 6,
    'goals': 7,
    'assists': 8,
    'goals_pens': 9,
    'pens_made': 10,
    'pens_att': 11,
    'cards_yellow': 12,
    'cards_red': 13,
    'goals_per90': 14,
    'assists_per90': 15,
    'goals_assists_per90': 16,
    'goals_pens_per90': 17,
    'goals_assists_pens_per90': 18,
    'xg': 19,
    'npxg': 20,
    'xa': 21,
    'xa_per90': 22,
    'xg_per90': 23,
    'xg_xa_per90': 24,
    'npxg_per90': 25,
    'npxg_xa_per90': 26
}

all_statistics_td_column_index = {
    'nationality': 0,
    'position': 1,
    'age': 2,
    'games': 3,
    'games_starts': 4,
    'minutes': 5,
    'minutes_90s': 6,
    'goals': 7,
    'assists': 8,
    'goals_pens': 9,
    'pens_made': 10,
    'pens_att': 11,
    'cards_yellow': 12,
    'cards_red': 13,
    'goals_per90': 14,
    'assists_per90': 15,
    'goals_assists_per90': 16,
    'goals_pens_per90': 17,
    'goals_assists_pens_per90': 18,
    'xg': 19,
    'npxg': 20,
    'xa': 21,
    'xa_per90': 22,
    'xg_per90': 23,
    'xg_xa_per90': 24,
    'npxg_per90': 25,
    'npxg_xa_per90': 26
}

player_nationality_en_dict = {
    'ENG': '英格兰',
    'BRA': '巴西',
    'GER': '德国',
    'POR': '葡萄牙',
    'ESP': '西班牙',
    'UKR': '乌克兰',
    'ALG': '阿尔及利亚',
    'NED': '荷兰',
    'FRA': '法国',
    'BEL': '比利时',
    'ARG': '阿根廷',
    'USA': '美国'
}

player_name_en_dict = {
    'Rúben Dias': ['鲁本·迪亚斯', '迪亚斯'],
    'Rodri': ['罗德里', '罗德里'],
    'Ederson': ['埃德森', '埃德森'],
    'Raheem Sterling': ['拉希姆·斯特林', '斯特林'],
    'João Cancelo': ['若奥·坎赛洛', '坎赛洛'],
    'Phil Foden': ['菲尔·福登', '福登'],
    'Riyad Mahrez': ['里亚德·马赫雷斯', '马赫雷斯'],
    'Kyle Walker': ['凯尔·沃克', '凯尔·沃克'],
    'Kevin De Bruyne': ['凯文·德布劳内', '德布劳内'],
    'İlkay Gündoğan': ['伊尔卡伊·京多安', '京多安'],
    'Bernardo Silva': ['贝尔纳多·席尔瓦', 'B席'],
    'John Stones': ['约翰·斯通斯', '斯通斯'],
    'Gabriel Jesus': ['加布里埃尔·热苏斯', '热苏斯'],
    'Ferrán Torres': ['费兰·托雷斯', '托雷斯'],
    'Fernandinho': ['费尔南迪尼奥', '费尔南迪尼奥'],
    'Oleksandr Zinchenko': ['亚历山大·津琴科', '津琴科'],
    'Aymeric Laporte': ['埃梅里克·拉波尔特', '拉波尔特'],
    'Benjamin Mendy': ['本杰明·门迪', '门迪'],
    'Zack Steffen': ['扎克·斯特芬', '斯特芬'],
    'Nathan Aké': ['纳桑·阿克', '阿克'],
    'Eric García': ['埃里克·加西亚', '加西亚'],
    'Sergio Agüero': ['塞尔吉奥·阿圭罗', '阿圭罗'],
    'Taylor Harwood-Bellis': ['泰勒·哈伍德·贝利斯', '泰勒·哈伍德·贝利斯'],
    'Liam Delap': ['利亚姆·德拉普', '利亚姆·德拉普'],
    'Thomas Doyle': ['托马斯·多伊尔', '托马斯·多伊尔'],
    'Cole Palmer': ['科尔·帕尔默', '科尔·帕尔默'],
    'Felix Kalu Nmecha': ['费利克斯·恩梅查', '费利克斯·恩梅查'],
    'Adrian Bernabe': ['阿德里安·贝尔纳贝', '阿德里安·贝尔纳贝'],
    'Luke Mbete-Tatu': ['卢克·姆贝特', '卢克·姆贝特'],
    'James Trafford': ['詹姆斯·特拉福德', '詹姆斯·特拉福德'],
    'Scott Carson': ['斯科特·卡森', '卡森'],
    'Claudio Gomes': ['克劳迪奥·戈麦斯', '克劳迪奥·戈麦斯']
}